using System.IO;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ShopPOS.Domain.Models;
using ShopPOS.WPF.Assets;

namespace ShopPOS.WPF.Services.Reports;

public sealed class QuestPdfLedgerReportService : ILedgerPdfReportService
{
    private const string GridLineColor = "#E2E8F0";
    private const string HeaderBlue = "#27BEF5";
    private const string HeaderDivider = "#1DA8E0";
    private const string ZebraFill = "#F8FAFC";
    private const string TextDark = "#0F172A";
    private const string TextMuted = "#475569";

    private readonly PosHardwareOptions _hardware;

    public QuestPdfLedgerReportService(PosHardwareOptions hardware) => _hardware = hardware;

    public void GenerateVendorLedger(VendorLedgerReportData data, string outputPath)
    {
        Document.Create(document =>
        {
            document.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(28);
                page.DefaultTextStyle(x => x.FontSize(9).FontColor(TextDark));

                page.Header().Element(c => ComposeReportHeader(c, data.ShopTitle, data.ShopContactLine, data.ExportDate, "Vendor Ledger Report"));
                page.Content().PaddingTop(12).Column(column =>
                {
                    column.Spacing(10);
                    column.Item().Element(c => ComposeVendorMetadata(c, data));
                    column.Item().Element(c => ComposeVendorSummary(c, data));
                    column.Item().PaddingTop(4).Text("Transaction History").SemiBold().FontSize(11).FontColor(HeaderBlue);
                    column.Item().Element(c => ComposeVendorTable(c, data.Lines));
                });
                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by KitchenMart.pk POS  •  Page ");
                    text.CurrentPageNumber();
                    text.Span(" of ");
                    text.TotalPages();
                });
            });
        }).GeneratePdf(outputPath);
    }

    public void GenerateWorkerReport(WorkerEmployeeReportData data, string outputPath)
    {
        var period = new DateTime(data.ReportYear, data.ReportMonth, 1).ToString("MMMM yyyy");

        Document.Create(document =>
        {
            document.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(28);
                page.DefaultTextStyle(x => x.FontSize(9).FontColor(TextDark));

                page.Header().Element(c => ComposeReportHeader(c, data.ShopTitle, data.ShopContactLine, data.ExportDate, $"Employee Report — {period}"));
                page.Content().PaddingTop(12).Column(column =>
                {
                    column.Spacing(10);
                    column.Item().Element(c => ComposeWorkerMetadata(c, data));
                    column.Item().Element(c => ComposeWorkerSummary(c, data));
                    column.Item().PaddingTop(4).Text("Operational Ledger Detail").SemiBold().FontSize(11).FontColor(HeaderBlue);
                    column.Item().Element(c => ComposeWorkerTable(c, data.DetailLines));
                });
                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by KitchenMart.pk POS  •  Page ");
                    text.CurrentPageNumber();
                    text.Span(" of ");
                    text.TotalPages();
                });
            });
        }).GeneratePdf(outputPath);
    }

    private void ComposeReportHeader(IContainer container, string title, string contactLine, DateTime exportDate, string reportTitle)
    {
        container.Column(column =>
        {
            column.Item().Row(row =>
            {
                row.ConstantItem(56).Height(56).Element(logo =>
                {
                    var bytes = LoadLogoBytes();
                    if (bytes is { Length: > 0 })
                        logo.Image(bytes).FitArea();
                    else
                        logo.Background(Colors.Grey.Lighten3);
                });

                row.RelativeItem().PaddingLeft(12).Column(info =>
                {
                    info.Item().Text(title).Bold().FontSize(14).FontColor(TextDark);
                    info.Item().Text("KitchenMart.pk").SemiBold().FontSize(10).FontColor(HeaderBlue);
                    info.Item().Text(contactLine).FontSize(9).FontColor(TextMuted);
                    info.Item().PaddingTop(4).Text(reportTitle).Bold().FontSize(11).FontColor(TextDark);
                });

                row.ConstantItem(120).AlignRight().Column(right =>
                {
                    right.Item().Text("Export Date").SemiBold().FontSize(8).FontColor(TextMuted);
                    right.Item().Text(exportDate.ToString("dd MMM yyyy, hh:mm tt")).FontSize(9);
                });
            });

            column.Item().PaddingTop(8).LineHorizontal(1).LineColor(HeaderBlue);
        });
    }

    private static void ComposeVendorMetadata(IContainer container, VendorLedgerReportData data)
    {
        container.Border(1).BorderColor(GridLineColor).Background(Colors.White).Padding(10).Column(column =>
        {
            column.Spacing(4);
            column.Item().Text("Vendor Information").SemiBold().FontSize(10).FontColor(HeaderBlue);
            MetadataRow(column, "Vendor Name", data.VendorName);
            MetadataRow(column, "Phone", data.VendorPhone);
            MetadataRow(column, "Address", string.IsNullOrWhiteSpace(data.VendorAddress) ? "—" : data.VendorAddress);
        });
    }

    private static void ComposeWorkerMetadata(IContainer container, WorkerEmployeeReportData data)
    {
        container.Border(1).BorderColor(GridLineColor).Background(Colors.White).Padding(10).Column(column =>
        {
            column.Spacing(4);
            column.Item().Text("Employee Information").SemiBold().FontSize(10).FontColor(HeaderBlue);
            MetadataRow(column, "Worker Name", data.WorkerName);
            MetadataRow(column, "Designation", data.Designation);
            MetadataRow(column, "Joining Date", data.JoiningDateText);
            MetadataRow(column, "Contact", data.ContactPhone);
            MetadataRow(column, "Thumb Scanner", data.ThumbScannerStatus);
        });
    }

    private static void MetadataRow(ColumnDescriptor column, string label, string value)
    {
        column.Item().Row(row =>
        {
            row.ConstantItem(110).Text(label).FontColor(TextMuted).FontSize(8);
            row.RelativeItem().Text(value).FontSize(9);
        });
    }

    private static void ComposeVendorSummary(IContainer container, VendorLedgerReportData data)
    {
        container.Row(row =>
        {
            SummaryAmountBox(row.RelativeItem(), "Total Bills (Rs.)", data.TotalBillsText, "#EF4444");
            row.ConstantItem(8);
            SummaryAmountBox(row.RelativeItem(), "Total Cash Paid (Rs.)", data.TotalPaidText, HeaderBlue);
            row.ConstantItem(8);
            SummaryAmountBox(row.RelativeItem(), "Remaining Balance (Rs.)", data.RemainingBalanceText, TextDark);
        });
    }

    private static void ComposeWorkerSummary(IContainer container, WorkerEmployeeReportData data)
    {
        container.Column(column =>
        {
            column.Spacing(6);
            column.Item().Row(row =>
            {
                SummaryTextBox(row.RelativeItem(), "Days Present", data.PresentDaysText, HeaderBlue);
                row.ConstantItem(6);
                SummaryTextBox(row.RelativeItem(), "Days Absent", data.AbsentDaysText, "#EF4444");
                row.ConstantItem(6);
                SummaryTextBox(row.RelativeItem(), "Leave Days", data.LeaveDaysText, TextMuted);
                row.ConstantItem(6);
                SummaryTextBox(row.RelativeItem(), "Total OT Hours", data.TotalOvertimeHoursText, TextDark);
            });
            column.Item().Row(row =>
            {
                SummaryAmountBox(row.RelativeItem(), "Total Advance Taken (Rs.)", data.TotalAdvanceText, "#EF4444");
                row.ConstantItem(8);
                SummaryAmountBox(row.RelativeItem(), "Final Payable Salary (Rs.)", data.FinalPayableSalaryText, HeaderBlue);
            });
        });
    }

    private static void SummaryTextBox(IContainer container, string label, string value, string accent)
    {
        container.Border(1).BorderColor(GridLineColor).Background(Colors.White).Padding(8).Column(col =>
        {
            col.Item().AlignLeft().Text(label).FontSize(8).FontColor(TextMuted);
            col.Item().PaddingTop(2).AlignLeft().Text(value).Bold().FontSize(11).FontColor(accent);
        });
    }

    private static void SummaryAmountBox(IContainer container, string label, string amountNumber, string accent)
    {
        container.Border(1).BorderColor(GridLineColor).Background(Colors.White).Padding(8).Column(col =>
        {
            col.Item().AlignLeft().Text(label).FontSize(8).FontColor(TextMuted);
            col.Item().PaddingTop(2).PaddingRight(12).AlignRight().Text(amountNumber).Bold().FontSize(11).FontColor(accent);
        });
    }

    private static void ComposeVendorTable(IContainer container, IReadOnlyList<VendorLedgerReportLine> lines)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.ConstantColumn(58);
                columns.RelativeColumn(1.2f);
                columns.RelativeColumn(1.4f);
                columns.RelativeColumn(1.1f);
                columns.RelativeColumn(1f);
                columns.RelativeColumn(1f);
                columns.RelativeColumn(1.1f);
            });

            table.Header(header =>
            {
                HeaderCellLeft(header.Cell(), "Date");
                HeaderCellLeft(header.Cell(), "Invoice / Bill");
                HeaderCellLeft(header.Cell(), "Description");
                HeaderCellRight(header.Cell(), "Prev. Balance (Rs.)");
                HeaderCellRight(header.Cell(), "Total Bill (Rs.)");
                HeaderCellRight(header.Cell(), "Cash Paid (Rs.)");
                HeaderCellRight(header.Cell(), "Remaining (Rs.)");
            });

            if (lines.Count == 0)
            {
                table.Cell().ColumnSpan(7).Element(c => TextBodyCell(c, false))
                    .AlignCenter().Text("No ledger transactions recorded.").FontColor(TextMuted).Italic();
                return;
            }

            for (var i = 0; i < lines.Count; i++)
            {
                var line = lines[i];
                var alt = i % 2 == 1;
                TextBodyCell(table.Cell(), alt).AlignLeft().Text(line.DateText);
                TextBodyCell(table.Cell(), alt).AlignLeft().Text(line.InvoiceNumber);
                TextBodyCell(table.Cell(), alt).AlignLeft().Text(line.Description);
                AmountBodyCell(table.Cell(), alt).AlignRight().Text(line.PreviousBalanceText);
                AmountBodyCell(table.Cell(), alt).AlignRight().Text(line.TotalBillText);
                AmountBodyCell(table.Cell(), alt).AlignRight().Text(line.CashPaidText);
                AmountBodyCell(table.Cell(), alt).AlignRight().Text(line.RemainingBalanceText);
            }
        });
    }

    private static void ComposeWorkerTable(IContainer container, IReadOnlyList<WorkerEmployeeReportLine> lines)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.ConstantColumn(58);
                columns.RelativeColumn(1f);
                columns.RelativeColumn(1.6f);
                columns.ConstantColumn(48);
                columns.ConstantColumn(48);
                columns.ConstantColumn(44);
                columns.RelativeColumn(1f);
            });

            table.Header(header =>
            {
                HeaderCellLeft(header.Cell(), "Date");
                HeaderCellLeft(header.Cell(), "Type");
                HeaderCellLeft(header.Cell(), "Details");
                HeaderCellLeft(header.Cell(), "In");
                HeaderCellLeft(header.Cell(), "Out");
                HeaderCellLeft(header.Cell(), "OT");
                HeaderCellRight(header.Cell(), "Amount (Rs.)");
            });

            if (lines.Count == 0)
            {
                table.Cell().ColumnSpan(7).Element(c => TextBodyCell(c, false))
                    .AlignCenter().Text("No operational records for this period.").FontColor(TextMuted).Italic();
                return;
            }

            for (var i = 0; i < lines.Count; i++)
            {
                var line = lines[i];
                var alt = i % 2 == 1;
                TextBodyCell(table.Cell(), alt).AlignLeft().Text(line.DateText);
                TextBodyCell(table.Cell(), alt).AlignLeft().Text(line.EntryType);
                TextBodyCell(table.Cell(), alt).AlignLeft().Text(line.Description);
                TextBodyCell(table.Cell(), alt).AlignLeft().Text(line.TimeInText);
                TextBodyCell(table.Cell(), alt).AlignLeft().Text(line.TimeOutText);
                TextBodyCell(table.Cell(), alt).AlignLeft().Text(line.OvertimeHoursText);
                AmountBodyCell(table.Cell(), alt).AlignRight().Text(line.AmountText);
            }
        });
    }

    private static void HeaderCellLeft(IContainer container, string text)
    {
        container.Background(HeaderBlue)
            .Border(0.5f).BorderColor(HeaderDivider)
            .PaddingTop(6).PaddingBottom(6).PaddingLeft(4).PaddingRight(4)
            .AlignLeft()
            .DefaultTextStyle(x => x.FontColor(Colors.White).SemiBold().FontSize(8))
            .Text(text);
    }

    private static void HeaderCellRight(IContainer container, string text)
    {
        container.Background(HeaderBlue)
            .Border(0.5f).BorderColor(HeaderDivider)
            .PaddingTop(6).PaddingBottom(6).PaddingLeft(4).PaddingRight(12)
            .AlignRight()
            .DefaultTextStyle(x => x.FontColor(Colors.White).SemiBold().FontSize(8))
            .Text(text);
    }

    private static IContainer TextBodyCell(IContainer container, bool alternate) =>
        container.Background(alternate ? ZebraFill : Colors.White)
            .Border(0.5f).BorderColor(GridLineColor)
            .PaddingTop(4).PaddingBottom(4).PaddingLeft(4).PaddingRight(4)
            .DefaultTextStyle(x => x.FontSize(8).FontColor(TextDark));

    private static IContainer AmountBodyCell(IContainer container, bool alternate) =>
        container.Background(alternate ? ZebraFill : Colors.White)
            .Border(0.5f).BorderColor(GridLineColor)
            .PaddingTop(4).PaddingBottom(4).PaddingLeft(4).PaddingRight(12)
            .DefaultTextStyle(x => x.FontSize(8).FontColor(TextDark));

    private byte[]? LoadLogoBytes()
    {
        try
        {
            using var stream = LogoHelper.OpenLogoStream(_hardware);
            if (stream is null)
                return null;

            using var memory = new MemoryStream();
            stream.CopyTo(memory);
            return memory.ToArray();
        }
        catch
        {
            return null;
        }
    }
}
